package carRental

// Bill represents the billing details for a reservation.
type Bill struct {
	BillID         int
	ReservationID  int
	UserID         int
	VehicleID      int
	TotalAmount    float64
	DiscountAmount float64
	TaxAmount      float64
	FinalAmount    float64
	PaymentStatus  string // Paid, Unpaid
}

// GenerateBill generates a bill for the reservation.
func GenerateBill(reservation Reservation) Bill {
	const taxRate = 0.1
	discountAmount := 0.0 // Example: apply discounts if necessary
	taxAmount := reservation.TotalAmount * taxRate
	finalAmount := reservation.TotalAmount + taxAmount - discountAmount

	bill := Bill{
		BillID:         1, // This would normally be generated by the system
		ReservationID:  reservation.ReservationID,
		UserID:         reservation.UserID,
		VehicleID:      reservation.VehicleID,
		TotalAmount:    reservation.TotalAmount,
		DiscountAmount: discountAmount,
		TaxAmount:      taxAmount,
		FinalAmount:    finalAmount,
		PaymentStatus:  "Unpaid",
	}

	return bill
}
