package carRental

import (
	"time"
)

// Reservation represents a booking made by a user for a vehicle.
type Reservation struct {
	ReservationID int
	UserID        int
	VehicleID     int
	StoreID       int
	LocationID    int
	StartDate     time.Time
	EndDate       time.Time
	TotalAmount   float64
	Status        string // Reserved, Completed, Cancelled
}

// MakeReservation creates a reservation for a selected vehicle.
func MakeReservation(user User, vehicle Vehicle, store Store, location Location, startDate, endDate time.Time) Reservation {
	days := endDate.Sub(startDate).Hours() / 24
	totalAmount := vehicle.GetPricePerDay() * days

	// Mark the vehicle as reserved
	vehicle.SetStatus("Reserved")

	reservation := Reservation{
		ReservationID: 1, // This would normally be generated by the system
		UserID:        user.UserID,
		VehicleID:     vehicle.GetID(),
		StoreID:       store.StoreID,
		LocationID:    location.LocationID,
		StartDate:     startDate,
		EndDate:       endDate,
		TotalAmount:   totalAmount,
		Status:        "Reserved",
	}

	return reservation
}
